In [1]:
import numpy as np

In [2]:
a = np.arange(0, 18, 1); a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [3]:
c = np.append(a, 100); c

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17, 100])

In [4]:
downsample_ratio = int(10.0 / 2.0)
middle_point = downsample_ratio // 2  # find the middle of the group

# if downsample_ratio is even, the middle is between two elements.
# in this case, we choose the one after the exact middle.
if downsample_ratio % 2 == 0:
    middle_point += 1

# ensure the slice does not exceed the array's length
if middle_point >= len(a):
    middle_point = len(a) - 1

In [5]:
b = a[middle_point::downsample_ratio]; b

array([ 2,  7, 12, 17])

In [6]:
d = a[:-1]; d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [8]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])